<?php

require __DIR__ . "/vendor/autoload.php";

use Dompdf\Dompdf;
use Dompdf\Options;

ini_set("display_errors", true);
ini_set("error_log", "phperr.log");
ini_set("log_errors", true);
error_reporting(E_ALL);
$_dompdf_show_warnings = true; // record warnings generated by Dompdf
$_dompdf_debug = false; // output frame details for every frame in the document
$_DOMPDF_DEBUG_TYPES = [
    'page-break' => false // record information about page break determination
];


$options = new Options;
$options->setChroot(__DIR__);
$options->isRemoteEnabled(true);
$options->setFontDir(__DIR__);
$options->setFontCache(__DIR__);
$options->setTempDir(__DIR__);
$options->setIsRemoteEnabled(true);


$dompdf = new Dompdf($options);

$html = file_get_contents("template.html");


$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream();